### ISSUE TITLE
This plugin read error, with GitBucket 4.26.0 newer.

### ISSUE THREAD

**Issue by ShinoharaTa** [mrkm4ntr/gitbucket-network-plugin#13]
GitBucket New release version is using Semantic Version 2.0 at all plugins.
but the plugins not supported semver. Please change version system.

And GitBucket issues. [https://github.com/gitbucket/gitbucket/issues/2090](https://github.com/gitbucket/gitbucket/issues/2090)
Supported non using semver plugins. at 4.27.0

**Comment by mrkm4ntr** [comment]
Thank you for reporting.
1.6.0 has been released.
https://github.com/mrkm4ntr/gitbucket-network-plugin/releases/tag/1.6.0

**Comment by ShinoharaTa** [comment]
Thank you for newer GitBucket supported.

**Comment by source-c** [comment]
Thanks. Works just fine!

**Comment by chemacortes** [comment]
Great job!
Still missing at https://plugins.gitbucket-community.org

**Comment by mrkm4ntr** [comment]
Plugin registry does not support third-party plugins yet...

> For now, only the plugins under the GitBucket organization are being registered and automatically built. However we want extend this, to be able to register and build any third-party GitBucket plugin as well. 

See https://gitbucket.github.io/gitbucket-news/gitbucket/2018/06/20/plugin-registry-launched.html

**Comment by takezoe** [comment]
We are preparing third party plugins support now. Plesse wait for a while!
