### ISSUE TITLE
Plugin "1.6.0" still displays as "1.5"

### ISSUE THREAD

**Issue by PaulAdams-Conti** [mrkm4ntr/gitbucket-network-plugin#14]
Having updated to GitBucket 4.26.0 I had to update network plugin as server failed to start. After updating the plugin and restarting GitBucket, plugins page still shows "1.5" instead of "1.6.0"

**Comment by mrkm4ntr** [comment]
Thank you for reporting. 1.6.1 has been released.
This version fixes this.
