### ISSUE TITLE
Line connection for All Branches is wrong in certain cases

### ISSUE THREAD

**Issue by Hidetchi** [mrkm4ntr/gitbucket-network-plugin#15]
Hi,
First of all, thank you very much for the great work of developing this wonderful plugin.
I would like to report one issue I found in "All Branches".

**Case 1 (working fine)**
1.  First you were at HEAD of master
2. Create a new branch and make one commit
3. Come back to master and make one commit

![one_commit_by_branch](https://user-images.githubusercontent.com/161887/43042102-4db389da-8daf-11e8-8d2d-46773dc34510.jpg)

**Case 2 (how to reproduce the issue)**
1. First you were at HEAD of master
2. Create a new branch and **make multiple commits**
3. Come back to master and make one commit

![two_commits_by_branch](https://user-images.githubusercontent.com/161887/43042103-5bf5e2c2-8daf-11e8-972f-42fc6efe00a8.jpg)

The correct view would be like this below. (manually modified by an image editor)
![two_commits_by_branch_should_be](https://user-images.githubusercontent.com/161887/43042104-5f811d08-8daf-11e8-9726-dfec137aa980.jpg)

I hope this helps.

**Comment by mrkm4ntr** [comment]
@Hidetchi Thank you for reporting.
Please give me some time to investigate.

**Comment by Hidetchi** [comment]
I have looked a little bit more into this issue.
If I highlight the SVG path emerging from the final commit by making the line thicker and changing the color to red, it becomes like this.
![image](https://user-images.githubusercontent.com/161887/89749759-0d6fbc00-db04-11ea-8521-2ea3714ed29e.png)

As you can see, the line actually goes all the way to the first commit.
This means that the "parent" node of the final commit is chosen correctly.
The problem is simply that the "lane" attribute of this parent (= the first commit) is wrong for some reason.
(The "lane" of the first commit should be "+0", but it is mistakenly being "+1", I supose. )

It looks like it is coming from Line #52 in https://github.com/mrkm4ntr/gitbucket-network-plugin/blob/master/src/main/scala/mrkm4ntr/gitbucket/network/controller/NetworkController.scala

> Commit(
>    ....
>   plotCommit.getParents.toList.map { revCommit =>
>                 tail.find { case (p, _) => p.getId == revCommit.getId } map { case (p, i) => Parent(i, p.getLane.getPosition) }
>        },

Maybe we need to look into what **getLane.getPosition** is doing here?
