### ISSUE TITLE
Release for Version 4.32

### ISSUE THREAD

**Issue by pgollor** [mrkm4ntr/gitbucket-network-plugin#18]
Is tehre any plan to create a workin version with Gitbucket 4.32? Since 4.32 gitbucket is using Scala 2.13.0 and Scalatra 2.7.0.

It would be great if the use of the plugin would be possible again.

**Comment by SIkebe** [comment]
Waiting for #17 to be merged.

@mrkm4ntr Could you review above PR?

**Comment by pgollor** [comment]
Okay sorry, i will wait, i overlooked the pull request sorry.
