### ISSUE TITLE
1.7.0 release is missing jar file

### ISSUE THREAD

**Issue by SIkebe** [mrkm4ntr/gitbucket-network-plugin#19]
@mrkm4ntr Thank you for 1.7.0 release! Could you also upload the 1.7.0 jar file to the release page?

**Comment by mrkm4ntr** [comment]
Oops, I didn't notice this. I will fix it.

**Comment by mrkm4ntr** [comment]
@SIkebe Done. Please check it!

**Comment by SIkebe** [comment]
Thanks! It worked.
