### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by kyrahabattoir** [mrkm4ntr/gitbucket-network-plugin#2]
I get a popup "TypeError: NetworkError when attempting to fetch resource."

This is happening on my setup, when trying to access the network section.

I'm using Gitbucket 4.8 on port 8080 with Nginx acting as a proxy for it on port 80.

**Comment by mrkm4ntr** [comment]
I cannot get that error when I try it in  [plugin demo site](https://gitbucket-community.herokuapp.com/).
Can you show me more detail about the error?  
What browser did you use?

**Comment by kyrahabattoir** [comment]
I wish I had more infos about it, I'm using firefox 50.1.0

Shit i figured out what the issue was, i was blocking some specific content.

I don't know why i was convinced that this was an issue with my server setup.
