### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 when loading Network page

### ISSUE THREAD

**Issue by zsmahi** [mrkm4ntr/gitbucket-network-plugin#24]
Hello gitbucket-network-plugin team,

I'am new to gitbucket and its plugins, I installed today your plugin using the jar file on release, when trying to run it it shows the error message SyntaxError: Unexpected token < in JSON at position 0 as an alert (as shown below)

Can you help me to solve this issue ? 

I'm running gitbucket on tomcat 9 under windows 10. thanks in advance :)

![image](https://user-images.githubusercontent.com/2100091/89518363-18141380-d7db-11ea-9bcb-dfb0b8e44266.png)

**Comment by SIkebe** [comment]
dup of #22 ?

**Comment by zsmahi** [comment]
> dup of #22 ?

Hello Slkebe, 
I didn't upgrade gitbucket it's a new installation.

**Comment by SIkebe** [comment]
>I didn't upgrade gitbucket it's a new installation.

@zsmahi Which version of GitBucket are you using?

**Comment by zsmahi** [comment]
> > I didn't upgrade gitbucket it's a new installation.
> 
> @zsmahi Which version of GitBucket are you using?

@SIkebe I'm using the version 4.34.0

**Comment by SIkebe** [comment]
Then, the same version as #22. It's likely to be a same issue.

**Comment by zsmahi** [comment]
OK thanks , so I should wait until your pull request #23 be merged and build from source directly

**Comment by SIkebe** [comment]
@mrkm4ntr Hi! Could you review #23?

**Comment by mrkm4ntr** [comment]
@zsmahi @SIkebe I merged #23 and created new release. Please check it.

**Comment by zsmahi** [comment]
@mrkm4ntr thanks, I'm using the last version now 👍 😄
