### ISSUE TITLE
Doesn't work on gitbucket 4.38.0

### ISSUE THREAD

**Issue by Nunocky** [mrkm4ntr/gitbucket-network-plugin#34]
I get an error like this when I try to view the network page.
In gitbucket 4.38.0, multiple Assignees can be specified, and it seems that it is the effect.

```
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

![スクリーンショット 2022-09-07 14 37 48](https://user-images.githubusercontent.com/750091/188797608-695e5ec3-4040-4bfb-add0-5d2fdd55d183.png)

**Comment by mrkm4ntr** [comment]
Thank you for the report. Unfortunately I cannot reproduce this with issue assigned multiple users.

**Comment by Nunocky** [comment]
I'm running gitbucket on apache tomcat 9. I will attach the catalina error log for your reference.

[catalina-network.txt](https://github.com/mrkm4ntr/gitbucket-network-plugin/files/9543686/catalina-network.txt)
