### ISSUE TITLE
No Support for latest releases of gitbucket

### ISSUE THREAD

**Issue by pozgo** [mrkm4ntr/gitbucket-network-plugin#5]
Please update.

**Comment by mrkm4ntr** [comment]
Version 1.2 has released.

**Comment by shiena** [comment]
@mrkm4ntr The plugin version still contains the snapshot.
https://github.com/mrkm4ntr/gitbucket-network-plugin/blob/e99dc4be20844cfa424170c9a0c7456a940de2eb/src/main/scala/Plugin.scala#L19
